name: MLPY-CI

on:
  push:
    paths:
      - 'Codes/Python/**'
      - 'Docker/**'
  workflow_dispatch:

jobs:

  mlpy:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
          context: .
          file: ./Docker/Dockerfile
          # platforms: linux/amd64,linux/arm64,linux/arm/v7         
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mlpy:latest
    -
      name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        repository: ${{ secrets.DOCKER_HUB_USERNAME }}/mlpy
        cache-from: type=gha
        cache-to: type=gha,mode=max

